[package]
name = "govee_collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.9"
futures = "0.3.17"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0.30"
